language: node_js
node_js:
  - 11.4

cache:
  yarn: true
  directories:
    - node_modules  

matrix:
  include:
    - node_js: "11.4"
      script: "yarn test"
      after_success: "yarn test-coveralls"    

sudo: false